import type { LanguageCode } from '@/components/velox/language-context'

export type AuthDictionary = {
  signInTitle: string
  signInSubtitle: string
  signUpTitle: string
  signUpSubtitle: string
  fullName: string
  namePlaceholder: string
  email: string
  password: string
  passwordPlaceholder: string
  referral: string
  referralPlaceholder: string
  checking: string
  invitedBy: string
  codeNotFound: string
  signIn: string
  createAccount: string
  noAccount: string
  register: string
  alreadyAccount: string
  forgotPassword: string
  forgotTitle: string
  forgotSubtitle: string
  sendResetLink: string
  resetSent: string
  backToSignIn: string
  resetTitle: string
  resetSubtitle: string
  newPassword: string
  confirmPassword: string
  resetPassword: string
  resetSuccess: string
  passwordMismatch: string
  invalidToken: string
  signInFailed: string
  signUpFailed: string
  genericError: string
}

const en: AuthDictionary = {
  signInTitle: 'Welcome back', signInSubtitle: 'Sign in and continue where you left off.',
  signUpTitle: 'Join the VELOX network', signUpSubtitle: 'Create your account and access the arbitrage terminal.',
  fullName: 'Full name', namePlaceholder: 'Your name', email: 'Email', password: 'Password',
  passwordPlaceholder: 'At least 8 characters', referral: 'Referral code (optional)', referralPlaceholder: 'E.g. ADAX12',
  checking: 'Checking', invitedBy: 'Invited by {name}', codeNotFound: 'Code not found',
  signIn: 'Sign in', createAccount: 'Create account', noAccount: "Don't have an account?", register: 'Register',
  alreadyAccount: 'Already have an account?', forgotPassword: 'Forgot password?',
  forgotTitle: 'Reset your password', forgotSubtitle: 'Enter your email address and we will send a secure reset link.',
  sendResetLink: 'Send reset link', resetSent: 'If this email is registered, a reset link has been sent.',
  backToSignIn: 'Back to sign in', resetTitle: 'Choose a new password', resetSubtitle: 'Set a new password of at least 8 characters.',
  newPassword: 'New password', confirmPassword: 'Confirm password', resetPassword: 'Update password',
  resetSuccess: 'Your password has been updated. You can now sign in.', passwordMismatch: 'Passwords do not match.',
  invalidToken: 'This reset link is invalid or has expired.', signInFailed: 'Sign in failed.', signUpFailed: 'Registration failed.', genericError: 'Something went wrong.',
}

const tr: AuthDictionary = {
  signInTitle: 'Tekrar hoş geldin', signInSubtitle: 'Hesabına giriş yap ve kaldığın yerden devam et.',
  signUpTitle: 'VELOX ağına katıl', signUpSubtitle: 'Hesabını oluştur ve arbitraj terminaline eriş.',
  fullName: 'Ad Soyad', namePlaceholder: 'Adınız', email: 'E-posta', password: 'Parola',
  passwordPlaceholder: 'En az 8 karakter', referral: 'Referans kodu (opsiyonel)', referralPlaceholder: 'Örn. ADAX12',
  checking: 'Kontrol ediliyor', invitedBy: '{name} tarafından davet', codeNotFound: 'Kod bulunamadı',
  signIn: 'Giriş yap', createAccount: 'Hesap oluştur', noAccount: 'Hesabın yok mu?', register: 'Kayıt ol',
  alreadyAccount: 'Zaten hesabın var mı?', forgotPassword: 'Şifremi unuttum',
  forgotTitle: 'Şifreni sıfırla', forgotSubtitle: 'E-posta adresini gir; güvenli sıfırlama bağlantısını gönderelim.',
  sendResetLink: 'Sıfırlama bağlantısı gönder', resetSent: 'Bu e-posta kayıtlıysa sıfırlama bağlantısı gönderildi.',
  backToSignIn: 'Giriş ekranına dön', resetTitle: 'Yeni şifre belirle', resetSubtitle: 'En az 8 karakterden oluşan yeni şifreni belirle.',
  newPassword: 'Yeni şifre', confirmPassword: 'Yeni şifre tekrar', resetPassword: 'Şifreyi güncelle',
  resetSuccess: 'Şifren güncellendi. Şimdi giriş yapabilirsin.', passwordMismatch: 'Şifreler aynı değil.',
  invalidToken: 'Bu sıfırlama bağlantısı geçersiz veya süresi dolmuş.', signInFailed: 'Giriş başarısız oldu.', signUpFailed: 'Kayıt başarısız oldu.', genericError: 'Bir hata oluştu.',
}

const translations: Record<LanguageCode, Partial<AuthDictionary>> = {
  tr,
  en,
  ru: { signInTitle:'С возвращением',signInSubtitle:'Войдите и продолжайте работу.',signUpTitle:'Присоединиться к сети VELOX',signUpSubtitle:'Создайте аккаунт и откройте арбитражный терминал.',fullName:'Имя и фамилия',namePlaceholder:'Ваше имя',email:'Эл. почта',password:'Пароль',passwordPlaceholder:'Минимум 8 символов',referral:'Реферальный код (необязательно)',referralPlaceholder:'Напр. ADAX12',checking:'Проверка',invitedBy:'Приглашение от {name}',codeNotFound:'Код не найден',signIn:'Войти',createAccount:'Создать аккаунт',noAccount:'Нет аккаунта?',register:'Регистрация',alreadyAccount:'Уже есть аккаунт?',forgotPassword:'Забыли пароль?',forgotTitle:'Сброс пароля',forgotSubtitle:'Введите адрес электронной почты, и мы отправим защищённую ссылку.',sendResetLink:'Отправить ссылку',resetSent:'Если адрес зарегистрирован, ссылка для сброса отправлена.',backToSignIn:'Вернуться ко входу',resetTitle:'Новый пароль',resetSubtitle:'Укажите новый пароль длиной не менее 8 символов.',newPassword:'Новый пароль',confirmPassword:'Подтвердите пароль',resetPassword:'Обновить пароль',resetSuccess:'Пароль обновлён. Теперь вы можете войти.',passwordMismatch:'Пароли не совпадают.',invalidToken:'Ссылка недействительна или устарела.',signInFailed:'Не удалось войти.',signUpFailed:'Не удалось зарегистрироваться.',genericError:'Произошла ошибка.' },
  uk: { signInTitle:'З поверненням',signInSubtitle:'Увійдіть і продовжуйте роботу.',signUpTitle:'Приєднатися до мережі VELOX',signUpSubtitle:'Створіть обліковий запис і відкрийте арбітражний термінал.',fullName:'Ім’я та прізвище',namePlaceholder:'Ваше ім’я',email:'Електронна пошта',password:'Пароль',passwordPlaceholder:'Щонайменше 8 символів',referral:'Реферальний код (необов’язково)',referralPlaceholder:'Напр. ADAX12',checking:'Перевірка',invitedBy:'Запрошення від {name}',codeNotFound:'Код не знайдено',signIn:'Увійти',createAccount:'Створити обліковий запис',noAccount:'Немає облікового запису?',register:'Реєстрація',alreadyAccount:'Вже маєте обліковий запис?',forgotPassword:'Забули пароль?',forgotTitle:'Скидання пароля',forgotSubtitle:'Введіть електронну пошту, і ми надішлемо захищене посилання.',sendResetLink:'Надіслати посилання',resetSent:'Якщо адресу зареєстровано, посилання надіслано.',backToSignIn:'Повернутися до входу',resetTitle:'Новий пароль',resetSubtitle:'Створіть пароль щонайменше з 8 символів.',newPassword:'Новий пароль',confirmPassword:'Підтвердьте пароль',resetPassword:'Оновити пароль',resetSuccess:'Пароль оновлено. Тепер можна увійти.',passwordMismatch:'Паролі не збігаються.',invalidToken:'Посилання недійсне або прострочене.',signInFailed:'Не вдалося увійти.',signUpFailed:'Не вдалося зареєструватися.',genericError:'Сталася помилка.' },
  es: { signInTitle:'Bienvenido de nuevo',signInSubtitle:'Inicia sesión y continúa donde lo dejaste.',signUpTitle:'Únete a la red VELOX',signUpSubtitle:'Crea tu cuenta y accede al terminal de arbitraje.',fullName:'Nombre completo',namePlaceholder:'Tu nombre',email:'Correo electrónico',password:'Contraseña',passwordPlaceholder:'Mínimo 8 caracteres',referral:'Código de referido (opcional)',referralPlaceholder:'Ej. ADAX12',checking:'Comprobando',invitedBy:'Invitado por {name}',codeNotFound:'Código no encontrado',signIn:'Iniciar sesión',createAccount:'Crear cuenta',noAccount:'¿No tienes cuenta?',register:'Registrarse',alreadyAccount:'¿Ya tienes cuenta?',forgotPassword:'¿Olvidaste tu contraseña?',forgotTitle:'Restablecer contraseña',forgotSubtitle:'Introduce tu correo y enviaremos un enlace seguro.',sendResetLink:'Enviar enlace',resetSent:'Si el correo está registrado, se envió el enlace.',backToSignIn:'Volver al inicio de sesión',resetTitle:'Nueva contraseña',resetSubtitle:'Define una contraseña de al menos 8 caracteres.',newPassword:'Nueva contraseña',confirmPassword:'Confirmar contraseña',resetPassword:'Actualizar contraseña',resetSuccess:'Contraseña actualizada. Ya puedes iniciar sesión.',passwordMismatch:'Las contraseñas no coinciden.',invalidToken:'El enlace no es válido o ha caducado.',signInFailed:'No se pudo iniciar sesión.',signUpFailed:'No se pudo registrar.',genericError:'Ocurrió un error.' },
  pt: { signInTitle:'Bem-vindo de volta',signInSubtitle:'Entre e continue de onde parou.',signUpTitle:'Entre na rede VELOX',signUpSubtitle:'Crie sua conta e acesse o terminal de arbitragem.',fullName:'Nome completo',namePlaceholder:'Seu nome',email:'E-mail',password:'Senha',passwordPlaceholder:'Pelo menos 8 caracteres',referral:'Código de indicação (opcional)',referralPlaceholder:'Ex. ADAX12',checking:'Verificando',invitedBy:'Convidado por {name}',codeNotFound:'Código não encontrado',signIn:'Entrar',createAccount:'Criar conta',noAccount:'Não tem uma conta?',register:'Cadastrar',alreadyAccount:'Já tem uma conta?',forgotPassword:'Esqueceu a senha?',forgotTitle:'Redefinir senha',forgotSubtitle:'Digite seu e-mail para receber um link seguro.',sendResetLink:'Enviar link',resetSent:'Se o e-mail estiver cadastrado, o link foi enviado.',backToSignIn:'Voltar ao login',resetTitle:'Nova senha',resetSubtitle:'Defina uma senha com pelo menos 8 caracteres.',newPassword:'Nova senha',confirmPassword:'Confirmar senha',resetPassword:'Atualizar senha',resetSuccess:'Senha atualizada. Agora você pode entrar.',passwordMismatch:'As senhas não coincidem.',invalidToken:'O link é inválido ou expirou.',signInFailed:'Falha ao entrar.',signUpFailed:'Falha ao cadastrar.',genericError:'Ocorreu um erro.' },
  de: { signInTitle:'Willkommen zurück',signInSubtitle:'Melden Sie sich an und machen Sie weiter.',signUpTitle:'Dem VELOX-Netzwerk beitreten',signUpSubtitle:'Konto erstellen und Arbitrage-Terminal öffnen.',fullName:'Vollständiger Name',namePlaceholder:'Ihr Name',email:'E-Mail',password:'Passwort',passwordPlaceholder:'Mindestens 8 Zeichen',referral:'Empfehlungscode (optional)',referralPlaceholder:'Z. B. ADAX12',checking:'Wird geprüft',invitedBy:'Eingeladen von {name}',codeNotFound:'Code nicht gefunden',signIn:'Anmelden',createAccount:'Konto erstellen',noAccount:'Noch kein Konto?',register:'Registrieren',alreadyAccount:'Bereits ein Konto?',forgotPassword:'Passwort vergessen?',forgotTitle:'Passwort zurücksetzen',forgotSubtitle:'E-Mail eingeben, um einen sicheren Link zu erhalten.',sendResetLink:'Link senden',resetSent:'Falls die E-Mail registriert ist, wurde ein Link gesendet.',backToSignIn:'Zurück zur Anmeldung',resetTitle:'Neues Passwort',resetSubtitle:'Legen Sie ein Passwort mit mindestens 8 Zeichen fest.',newPassword:'Neues Passwort',confirmPassword:'Passwort bestätigen',resetPassword:'Passwort aktualisieren',resetSuccess:'Passwort aktualisiert. Sie können sich jetzt anmelden.',passwordMismatch:'Passwörter stimmen nicht überein.',invalidToken:'Der Link ist ungültig oder abgelaufen.',signInFailed:'Anmeldung fehlgeschlagen.',signUpFailed:'Registrierung fehlgeschlagen.',genericError:'Ein Fehler ist aufgetreten.' },
  it: { signInTitle:'Bentornato',signInSubtitle:'Accedi e continua da dove eri rimasto.',signUpTitle:'Entra nella rete VELOX',signUpSubtitle:'Crea il tuo account e accedi al terminale.',fullName:'Nome completo',namePlaceholder:'Il tuo nome',email:'E-mail',password:'Password',passwordPlaceholder:'Almeno 8 caratteri',referral:'Codice referral (facoltativo)',referralPlaceholder:'Es. ADAX12',checking:'Verifica',invitedBy:'Invitato da {name}',codeNotFound:'Codice non trovato',signIn:'Accedi',createAccount:'Crea account',noAccount:'Non hai un account?',register:'Registrati',alreadyAccount:'Hai già un account?',forgotPassword:'Password dimenticata?',forgotTitle:'Reimposta password',forgotSubtitle:'Inserisci la tua e-mail per ricevere un link sicuro.',sendResetLink:'Invia link',resetSent:'Se l’e-mail è registrata, il link è stato inviato.',backToSignIn:'Torna all’accesso',resetTitle:'Nuova password',resetSubtitle:'Imposta una password di almeno 8 caratteri.',newPassword:'Nuova password',confirmPassword:'Conferma password',resetPassword:'Aggiorna password',resetSuccess:'Password aggiornata. Ora puoi accedere.',passwordMismatch:'Le password non coincidono.',invalidToken:'Il link non è valido o è scaduto.',signInFailed:'Accesso non riuscito.',signUpFailed:'Registrazione non riuscita.',genericError:'Si è verificato un errore.' },
  fr: { signInTitle:'Bon retour',signInSubtitle:'Connectez-vous et reprenez là où vous étiez.',signUpTitle:'Rejoindre le réseau VELOX',signUpSubtitle:'Créez votre compte et accédez au terminal.',fullName:'Nom complet',namePlaceholder:'Votre nom',email:'E-mail',password:'Mot de passe',passwordPlaceholder:'Au moins 8 caractères',referral:'Code de parrainage (facultatif)',referralPlaceholder:'Ex. ADAX12',checking:'Vérification',invitedBy:'Invité par {name}',codeNotFound:'Code introuvable',signIn:'Se connecter',createAccount:'Créer un compte',noAccount:'Pas encore de compte ?',register:'S’inscrire',alreadyAccount:'Vous avez déjà un compte ?',forgotPassword:'Mot de passe oublié ?',forgotTitle:'Réinitialiser le mot de passe',forgotSubtitle:'Saisissez votre e-mail pour recevoir un lien sécurisé.',sendResetLink:'Envoyer le lien',resetSent:'Si l’e-mail est enregistré, le lien a été envoyé.',backToSignIn:'Retour à la connexion',resetTitle:'Nouveau mot de passe',resetSubtitle:'Choisissez un mot de passe d’au moins 8 caractères.',newPassword:'Nouveau mot de passe',confirmPassword:'Confirmer le mot de passe',resetPassword:'Mettre à jour',resetSuccess:'Mot de passe mis à jour. Vous pouvez vous connecter.',passwordMismatch:'Les mots de passe ne correspondent pas.',invalidToken:'Le lien est invalide ou expiré.',signInFailed:'Échec de la connexion.',signUpFailed:'Échec de l’inscription.',genericError:'Une erreur est survenue.' },
  kk: { signInTitle:'Қайта қош келдіңіз',signInSubtitle:'Кіріп, жұмысыңызды жалғастырыңыз.',signUpTitle:'VELOX желісіне қосылыңыз',signUpSubtitle:'Тіркелгі ашып, арбитраж терминалына кіріңіз.',fullName:'Толық аты-жөні',namePlaceholder:'Атыңыз',email:'Электрондық пошта',password:'Құпиясөз',passwordPlaceholder:'Кемінде 8 таңба',referral:'Реферал коды (міндетті емес)',referralPlaceholder:'Мыс. ADAX12',checking:'Тексерілуде',invitedBy:'{name} шақырды',codeNotFound:'Код табылмады',signIn:'Кіру',createAccount:'Тіркелгі ашу',noAccount:'Тіркелгіңіз жоқ па?',register:'Тіркелу',alreadyAccount:'Тіркелгіңіз бар ма?',forgotPassword:'Құпиясөзді ұмыттыңыз ба?',forgotTitle:'Құпиясөзді қалпына келтіру',forgotSubtitle:'Қауіпсіз сілтеме алу үшін поштаңызды енгізіңіз.',sendResetLink:'Сілтеме жіберу',resetSent:'Пошта тіркелген болса, сілтеме жіберілді.',backToSignIn:'Кіруге оралу',resetTitle:'Жаңа құпиясөз',resetSubtitle:'Кемінде 8 таңбалық құпиясөз орнатыңыз.',newPassword:'Жаңа құпиясөз',confirmPassword:'Құпиясөзді растау',resetPassword:'Құпиясөзді жаңарту',resetSuccess:'Құпиясөз жаңартылды. Енді кіре аласыз.',passwordMismatch:'Құпиясөздер сәйкес емес.',invalidToken:'Сілтеме жарамсыз немесе мерзімі өткен.',signInFailed:'Кіру сәтсіз.',signUpFailed:'Тіркелу сәтсіз.',genericError:'Қате орын алды.' },
  bg: { signInTitle:'Добре дошли отново',signInSubtitle:'Влезте и продължете оттам, докъдето стигнахте.',signUpTitle:'Присъединете се към VELOX',signUpSubtitle:'Създайте профил и отворете арбитражния терминал.',fullName:'Име и фамилия',namePlaceholder:'Вашето име',email:'Имейл',password:'Парола',passwordPlaceholder:'Поне 8 знака',referral:'Реферален код (по избор)',referralPlaceholder:'Напр. ADAX12',checking:'Проверка',invitedBy:'Поканен от {name}',codeNotFound:'Кодът не е намерен',signIn:'Вход',createAccount:'Създай профил',noAccount:'Нямате профил?',register:'Регистрация',alreadyAccount:'Имате профил?',forgotPassword:'Забравена парола?',forgotTitle:'Нулиране на парола',forgotSubtitle:'Въведете имейла си за защитена връзка.',sendResetLink:'Изпрати връзка',resetSent:'Ако имейлът е регистриран, връзката е изпратена.',backToSignIn:'Назад към входа',resetTitle:'Нова парола',resetSubtitle:'Задайте парола с поне 8 знака.',newPassword:'Нова парола',confirmPassword:'Потвърдете паролата',resetPassword:'Обнови паролата',resetSuccess:'Паролата е обновена. Можете да влезете.',passwordMismatch:'Паролите не съвпадат.',invalidToken:'Връзката е невалидна или изтекла.',signInFailed:'Неуспешен вход.',signUpFailed:'Неуспешна регистрация.',genericError:'Възникна грешка.' },
  id: { signInTitle:'Selamat datang kembali',signInSubtitle:'Masuk dan lanjutkan dari tempat terakhir.',signUpTitle:'Bergabung dengan jaringan VELOX',signUpSubtitle:'Buat akun dan akses terminal arbitrase.',fullName:'Nama lengkap',namePlaceholder:'Nama Anda',email:'Email',password:'Kata sandi',passwordPlaceholder:'Minimal 8 karakter',referral:'Kode referral (opsional)',referralPlaceholder:'Contoh ADAX12',checking:'Memeriksa',invitedBy:'Diundang oleh {name}',codeNotFound:'Kode tidak ditemukan',signIn:'Masuk',createAccount:'Buat akun',noAccount:'Belum punya akun?',register:'Daftar',alreadyAccount:'Sudah punya akun?',forgotPassword:'Lupa kata sandi?',forgotTitle:'Atur ulang kata sandi',forgotSubtitle:'Masukkan email untuk menerima tautan aman.',sendResetLink:'Kirim tautan',resetSent:'Jika email terdaftar, tautan telah dikirim.',backToSignIn:'Kembali ke masuk',resetTitle:'Kata sandi baru',resetSubtitle:'Buat kata sandi minimal 8 karakter.',newPassword:'Kata sandi baru',confirmPassword:'Konfirmasi kata sandi',resetPassword:'Perbarui kata sandi',resetSuccess:'Kata sandi diperbarui. Silakan masuk.',passwordMismatch:'Kata sandi tidak sama.',invalidToken:'Tautan tidak valid atau kedaluwarsa.',signInFailed:'Gagal masuk.',signUpFailed:'Gagal mendaftar.',genericError:'Terjadi kesalahan.' },
  ar: { signInTitle:'مرحباً بعودتك',signInSubtitle:'سجّل الدخول وتابع من حيث توقفت.',signUpTitle:'انضم إلى شبكة VELOX',signUpSubtitle:'أنشئ حسابك وادخل إلى منصة المراجحة.',fullName:'الاسم الكامل',namePlaceholder:'اسمك',email:'البريد الإلكتروني',password:'كلمة المرور',passwordPlaceholder:'8 أحرف على الأقل',referral:'رمز الإحالة (اختياري)',referralPlaceholder:'مثال ADAX12',checking:'جارٍ التحقق',invitedBy:'دعوة من {name}',codeNotFound:'الرمز غير موجود',signIn:'تسجيل الدخول',createAccount:'إنشاء حساب',noAccount:'ليس لديك حساب؟',register:'إنشاء حساب',alreadyAccount:'لديك حساب بالفعل؟',forgotPassword:'نسيت كلمة المرور؟',forgotTitle:'إعادة تعيين كلمة المرور',forgotSubtitle:'أدخل بريدك لاستلام رابط آمن.',sendResetLink:'إرسال الرابط',resetSent:'إذا كان البريد مسجلاً فقد أرسل الرابط.',backToSignIn:'العودة إلى تسجيل الدخول',resetTitle:'كلمة مرور جديدة',resetSubtitle:'اختر كلمة مرور من 8 أحرف على الأقل.',newPassword:'كلمة المرور الجديدة',confirmPassword:'تأكيد كلمة المرور',resetPassword:'تحديث كلمة المرور',resetSuccess:'تم تحديث كلمة المرور. يمكنك تسجيل الدخول الآن.',passwordMismatch:'كلمتا المرور غير متطابقتين.',invalidToken:'الرابط غير صالح أو منتهي الصلاحية.',signInFailed:'تعذر تسجيل الدخول.',signUpFailed:'تعذر إنشاء الحساب.',genericError:'حدث خطأ.' },
  zh: { signInTitle:'欢迎回来',signInSubtitle:'登录并继续上次的操作。',signUpTitle:'加入 VELOX 网络',signUpSubtitle:'创建账户并进入套利终端。',fullName:'姓名',namePlaceholder:'您的姓名',email:'电子邮件',password:'密码',passwordPlaceholder:'至少 8 个字符',referral:'推荐码（可选）',referralPlaceholder:'例如 ADAX12',checking:'正在检查',invitedBy:'由 {name} 邀请',codeNotFound:'未找到推荐码',signIn:'登录',createAccount:'创建账户',noAccount:'还没有账户？',register:'注册',alreadyAccount:'已有账户？',forgotPassword:'忘记密码？',forgotTitle:'重置密码',forgotSubtitle:'输入电子邮件以接收安全重置链接。',sendResetLink:'发送重置链接',resetSent:'如果该邮箱已注册，重置链接已发送。',backToSignIn:'返回登录',resetTitle:'设置新密码',resetSubtitle:'请设置至少 8 个字符的新密码。',newPassword:'新密码',confirmPassword:'确认密码',resetPassword:'更新密码',resetSuccess:'密码已更新，现在可以登录。',passwordMismatch:'两次密码不一致。',invalidToken:'链接无效或已过期。',signInFailed:'登录失败。',signUpFailed:'注册失败。',genericError:'发生错误。' },
  hu: { signInTitle:'Üdv újra',signInSubtitle:'Jelentkezzen be, és folytassa ahol abbahagyta.',signUpTitle:'Csatlakozás a VELOX hálózathoz',signUpSubtitle:'Hozzon létre fiókot és nyissa meg a terminált.',fullName:'Teljes név',namePlaceholder:'Az Ön neve',email:'E-mail',password:'Jelszó',passwordPlaceholder:'Legalább 8 karakter',referral:'Ajánlókód (opcionális)',referralPlaceholder:'Pl. ADAX12',checking:'Ellenőrzés',invitedBy:'Meghívó: {name}',codeNotFound:'A kód nem található',signIn:'Bejelentkezés',createAccount:'Fiók létrehozása',noAccount:'Nincs még fiókja?',register:'Regisztráció',alreadyAccount:'Már van fiókja?',forgotPassword:'Elfelejtette a jelszót?',forgotTitle:'Jelszó visszaállítása',forgotSubtitle:'Adja meg e-mail-címét a biztonságos linkhez.',sendResetLink:'Link küldése',resetSent:'Ha az e-mail regisztrált, elküldtük a linket.',backToSignIn:'Vissza a bejelentkezéshez',resetTitle:'Új jelszó',resetSubtitle:'Állítson be legalább 8 karakteres jelszót.',newPassword:'Új jelszó',confirmPassword:'Jelszó megerősítése',resetPassword:'Jelszó frissítése',resetSuccess:'A jelszó frissült. Most már bejelentkezhet.',passwordMismatch:'A jelszavak nem egyeznek.',invalidToken:'A link érvénytelen vagy lejárt.',signInFailed:'Sikertelen bejelentkezés.',signUpFailed:'Sikertelen regisztráció.',genericError:'Hiba történt.' },
  fa: { signInTitle:'خوش آمدید',signInSubtitle:'وارد شوید و از همان‌جا ادامه دهید.',signUpTitle:'به شبکه VELOX بپیوندید',signUpSubtitle:'حساب بسازید و وارد پایانه آربیتراژ شوید.',fullName:'نام کامل',namePlaceholder:'نام شما',email:'ایمیل',password:'رمز عبور',passwordPlaceholder:'حداقل ۸ نویسه',referral:'کد معرف (اختیاری)',referralPlaceholder:'مثلاً ADAX12',checking:'در حال بررسی',invitedBy:'دعوت‌شده توسط {name}',codeNotFound:'کد پیدا نشد',signIn:'ورود',createAccount:'ساخت حساب',noAccount:'حساب ندارید؟',register:'ثبت‌نام',alreadyAccount:'از قبل حساب دارید؟',forgotPassword:'رمز عبور را فراموش کرده‌اید؟',forgotTitle:'بازنشانی رمز عبور',forgotSubtitle:'ایمیل را برای دریافت پیوند امن وارد کنید.',sendResetLink:'ارسال پیوند',resetSent:'اگر ایمیل ثبت شده باشد، پیوند ارسال شده است.',backToSignIn:'بازگشت به ورود',resetTitle:'رمز عبور جدید',resetSubtitle:'رمزی با حداقل ۸ نویسه تعیین کنید.',newPassword:'رمز عبور جدید',confirmPassword:'تأیید رمز عبور',resetPassword:'به‌روزرسانی رمز',resetSuccess:'رمز عبور به‌روزرسانی شد. اکنون وارد شوید.',passwordMismatch:'رمزها یکسان نیستند.',invalidToken:'پیوند نامعتبر یا منقضی است.',signInFailed:'ورود ناموفق بود.',signUpFailed:'ثبت‌نام ناموفق بود.',genericError:'خطایی رخ داد.' },
}

export function getAuthTranslations(language: LanguageCode): AuthDictionary {
  return { ...en, ...translations[language] }
}
