import { FileDown, TrendingUp } from 'lucide-react'
import { Panel, PanelHeader, StatTile } from '@/components/velox/primitives'
import { formatNumber, formatUSDT } from '@/lib/format'
import type { DemoDailyReport } from '@/lib/services/demo-report.service'

export function AdminDemoReports({ daily, endingCash }: { daily: DemoDailyReport[]; endingCash: number }) {
  const current = daily.at(-1)
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Demo Raporlama Merkezi</h1><p className="mt-1 text-sm text-muted-foreground">Faz 1 sentetik veri setinin gün sonu finans ve ağ büyüme görünümü. Gerçek finansal hareket oluşturmaz.</p></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-7"><StatTile label="Bugün giriş" value={formatUSDT(current?.deposits ?? 0, 2)} accent /><StatTile label="Yatırım kâr dağıtımı" value={formatUSDT(current?.memberAccrual ?? 0, 2)} /><StatTile label="Referral %6" value={formatUSDT(current?.referralExpense ?? 0, 2)} /><StatTile label="Network geliri" value={formatUSDT(current?.networkIncome ?? 0, 2)} /><StatTile label="Cashback" value={formatUSDT(current?.cashback ?? 0, 2)} /><StatTile label="Net K/Z" value={formatUSDT(current?.profitLoss ?? 0, 2)} /><StatTile label="Kasa devir" value={formatUSDT(endingCash, 2)} /></div>
    <Panel><PanelHeader title="Rapor çıktıları" right={<FileDown className="size-4 text-cyan" />} /><div className="grid gap-3 p-4 sm:grid-cols-2"><div className="rounded-lg border border-cyan/35 bg-cyan/5 p-4"><p className="font-semibold">Gün sonu finans</p><p className="mt-1 text-xs text-muted-foreground">Girişler, arbitraj brütü, üye tahakkuku, doğrudan referansın ilk yatırımından bir defalık %6, ödeme, ödeme kuyruğu, kasa ve K/Z.</p><div className="mt-3 flex gap-2"><a href="/api/admin/demo-reports/finance" className="rounded border border-cyan/50 px-2 py-1 text-xs font-medium text-cyan hover:bg-cyan/10">PDF indir</a><a href="/api/admin/demo-reports/finance?format=excel" className="rounded border border-cyan/50 px-2 py-1 text-xs font-medium text-cyan hover:bg-cyan/10">Excel indir</a></div></div><div className="rounded-lg border border-cyan/35 bg-cyan/5 p-4"><p className="font-semibold">Ağ büyümesi</p><p className="mt-1 text-xs text-muted-foreground">Günlük kayıt hızı, kümülatif ağ, büyüme yüzdesi ve kritik eşikler.</p><div className="mt-3 flex gap-2"><a href="/api/admin/demo-reports/growth" className="rounded border border-cyan/50 px-2 py-1 text-xs font-medium text-cyan hover:bg-cyan/10">PDF indir</a><a href="/api/admin/demo-reports/growth?format=excel" className="rounded border border-cyan/50 px-2 py-1 text-xs font-medium text-cyan hover:bg-cyan/10">Excel indir</a></div></div></div></Panel>
    <Panel className="p-0"><PanelHeader title="Günlük özet tablosu" right={<TrendingUp className="size-4 text-cyan" />} /><div className="overflow-x-auto"><table className="w-full min-w-[1330px] text-sm"><thead className="border-y border-border text-left text-xs text-muted-foreground"><tr>{['Tarih','Yeni kayıt','Toplam ağ','Giriş','Arbitraj','Yatırım kârı','Referral %6','Network','Cashback','Toplam dağıtım','Ödeme','Net K/Z','Kasa'].map((item) => <th key={item} className="px-4 py-3 font-medium">{item}</th>)}</tr></thead><tbody>{daily.map((row) => <tr key={row.date} className="border-b border-border/70"><td className="px-4 py-3">{row.date}</td><td className="px-4 py-3">{row.registrations}</td><td className="px-4 py-3">{row.cumulativeMembers}</td><td className="px-4 py-3 font-mono">{formatUSDT(row.deposits,2)}</td><td className="px-4 py-3 font-mono">{formatUSDT(row.arbitrageGross,2)}</td><td className="px-4 py-3 font-mono">{formatUSDT(row.memberAccrual,2)}</td><td className="px-4 py-3 font-mono">{formatUSDT(row.referralExpense,2)}</td><td className="px-4 py-3 font-mono">{formatUSDT(row.networkIncome,2)}</td><td className="px-4 py-3 font-mono">{formatUSDT(row.cashback,2)}</td><td className="px-4 py-3 font-mono">{formatUSDT(row.totalDistribution,2)}</td><td className="px-4 py-3 font-mono">{formatUSDT(row.automaticPayments,2)}</td><td className="px-4 py-3 font-mono text-emerald-300">{formatUSDT(row.profitLoss,2)}</td><td className="px-4 py-3 font-mono">{formatUSDT(row.closingCash,2)}</td></tr>)}</tbody></table></div></Panel>
  </div>
}
