export type ExportLanguageCode = 'tr' | 'en' | 'ru' | 'uk' | 'es' | 'pt' | 'de' | 'it' | 'fr' | 'kk' | 'bg' | 'id' | 'ar' | 'zh' | 'hu' | 'fa'

const supported = new Set<ExportLanguageCode>(['tr','en','ru','uk','es','pt','de','it','fr','kk','bg','id','ar','zh','hu','fa'])

export const exportLocales: Record<ExportLanguageCode, string> = {
  tr:'tr-TR', en:'en-US', ru:'ru-RU', uk:'uk-UA', es:'es-ES', pt:'pt-PT', de:'de-DE', it:'it-IT',
  fr:'fr-FR', kk:'kk-KZ', bg:'bg-BG', id:'id-ID', ar:'ar-SA', zh:'zh-CN', hu:'hu-HU', fa:'fa-IR',
}

export function normalizeExportLanguage(value: string | null | undefined): ExportLanguageCode {
  return value && supported.has(value as ExportLanguageCode) ? value as ExportLanguageCode : 'en'
}

export function exportLanguageFromRequest(request: Request): ExportLanguageCode {
  const urlLanguage = new URL(request.url).searchParams.get('lang')
  if (urlLanguage) return normalizeExportLanguage(urlLanguage)
  const match = request.headers.get('cookie')?.match(/(?:^|;\s*)velox-language=([^;]+)/)
  return normalizeExportLanguage(match?.[1])
}

const en = {
  receiptTitle:'INVESTMENT TRANSACTION RECEIPT', receiptSubtitle:'Verified digital asset deposit summary', documentNumber:'Document number', issueDate:'Issue date', confirmationDate:'Network confirmation date', transactionStatus:'Transaction status', confirmed:'Confirmed', memberInfo:'MEMBER INFORMATION', fullName:'Full name', email:'Email', investmentInfo:'INVESTMENT INFORMATION', investmentAmount:'Investment amount', network:'Network', receivingAddress:'Receiving address', transactionHash:'Transaction hash', electronicApproval:'Electronically approved', receiptNote:'This document summarizes a verified investment transaction on the VELOX platform. It is not an official tax invoice, profit guarantee or investment advice. The transaction hash can be verified independently on the relevant blockchain.', receiptFooter:'VELOX transaction receipt • Can be verified again from your platform account using the document number.',
  agreementTitle:'GENERAL PARTNER (GP) DEMO SUMMARY', agreementSubtitle:'Platform interface and document export example', demoReference:'DEMO REFERENCE NO.', demoDisclaimer:'This PDF is generated only to demonstrate the document view of the VELOX demo interface. It is not a binding agreement, investment solicitation, asset transfer, return guarantee or valid electronic signature.', party:'Party', role:'Role', documentNature:'Document type', demoPlatform:'VELOX Demo Platform', interfaceSummary:'Interface and training summary', participantRecord:'PARTICIPANT RECORD', userCode:'VELOX user code', clauses:'DEMO TERMS', purposeClause:'1. Purpose: This document demonstrates the visual operation of the GP contract screen and its personalized PDF export.', scopeClause:'2. Scope: No real money, wallet, trading, fundraising or asset transfer takes place in the demo environment.', approvalClause:'3. Approval: The seal and electronic approval area below is an interface example and is not a signature based on a qualified electronic certificate.', noLegalValidity:'ELECTRONIC DEMO APPROVAL - NO LEGAL VALIDITY', agreementFooter:'VELOX GP demo summary • This document is not an official contract or signed legal instrument.',
  financeTitle:'VELOX DEMO END-OF-DAY FINANCE REPORT', growthTitle:'VELOX DEMO NETWORK GROWTH REPORT', simulationNote:'Training and simulation data only. It is not a real payment, wallet or investment transaction.', date:'Date', newRegistrations:'New registrations', deposit:'Deposit USDT', arbitrageGross:'Gross arbitrage USDT', investmentDistribution:'Investment profit distribution USDT', referral:'Direct referral 6% USDT', networkIncome:'Network income USDT', cashback:'Cashback USDT', totalDistribution:'Total distribution USDT', automaticPayment:'Automatic payment USDT', paymentQueue:'Payment queue USDT', profitLoss:'Net P/L USDT', closingCash:'Closing cash USDT', totalNetwork:'Cumulative network', previousNetwork:'Previous-day network', growth:'Growth %', threshold:'Critical threshold', paymentDetails:'Payment / network details', member:'Member', type:'Type', amount:'Amount USDT', reference:'Reference', reportEnd:'End of report', noData:'No data', starting:'Start',
}

type Key = keyof typeof en
type Pack = Partial<Record<Key, string>>

const tr: Pack = {
  receiptTitle:'YATIRIM İŞLEM BELGESİ',receiptSubtitle:'Doğrulanmış dijital varlık yatırımı işlem özeti',documentNumber:'Belge numarası',issueDate:'Belge oluşturma tarihi',confirmationDate:'Ağ doğrulama tarihi',transactionStatus:'İşlem durumu',confirmed:'Doğrulandı',memberInfo:'ÜYE BİLGİLERİ',fullName:'Ad soyad',email:'E-posta',investmentInfo:'YATIRIM BİLGİLERİ',investmentAmount:'Yatırım tutarı',network:'Ağ',receivingAddress:'Alıcı adresi',transactionHash:'İşlem hash',electronicApproval:'Elektronik olarak onaylandı',receiptNote:'Bu belge VELOX platformundaki doğrulanmış yatırım işleminin özetidir. Resmî vergi faturası, kâr taahhüdü veya yatırım tavsiyesi değildir. İşlem hash değeri ilgili blok zinciri kaydından bağımsız olarak doğrulanabilir.',receiptFooter:'VELOX işlem belgesi • Belge numarası ile platform hesabınızdan tekrar doğrulanabilir.',
  agreementTitle:'GENERAL PARTNER (GP) DEMO ÖZETİ',agreementSubtitle:'Platform arayüzü ve belge çıktısı örneği',demoReference:'DEMO REFERANS NO.',demoDisclaimer:'Bu PDF yalnızca VELOX demo arayüzünün belge görünümünü göstermek için üretilmiştir. Bağlayıcı sözleşme, yatırım çağrısı, varlık devri, getiri taahhüdü veya geçerli elektronik imza içermez.',party:'Taraf',role:'Rol',documentNature:'Belge niteliği',demoPlatform:'VELOX Demo Platformu',interfaceSummary:'Arayüz ve eğitim özeti',participantRecord:'KATILIMCI KAYDI',userCode:'VELOX kullanıcı kodu',clauses:'DEMO MADDELER',purposeClause:'1. Amaç: Bu belge, GP odaklı sözleşme ekranı ile kişiye özel PDF çıktısının tasarımsal işleyişini gösterir.',scopeClause:'2. Kapsam: Demo ortamında gerçek para, cüzdan, alım-satım, fon toplama veya varlık aktarımı gerçekleştirilmez.',approvalClause:'3. Onay: Aşağıdaki kaşe ve elektronik onay alanı yalnızca arayüz örneğidir; nitelikli elektronik sertifikaya dayalı imza değildir.',noLegalValidity:'ELEKTRONİK DEMO ONAYI - HUKUKİ GEÇERLİLİĞİ YOKTUR',agreementFooter:'VELOX GP demo özeti • Bu belge resmî sözleşme veya imzalı hukukî evrak değildir.',
  financeTitle:'VELOX DEMO GÜN SONU FİNANS RAPORU',growthTitle:'VELOX DEMO AĞ BÜYÜME RAPORU',simulationNote:'Yalnız eğitim ve simülasyon verisidir. Gerçek ödeme, cüzdan veya yatırım hareketi değildir.',date:'Tarih',newRegistrations:'Yeni kayıt',deposit:'Giriş USDT',arbitrageGross:'Arbitraj brüt USDT',investmentDistribution:'Yatırım kâr dağıtımı USDT',referral:'Doğrudan referral %6 USDT',networkIncome:'Network geliri USDT',cashback:'Cashback USDT',totalDistribution:'Toplam dağıtım USDT',automaticPayment:'Otomatik ödeme USDT',paymentQueue:'Ödeme kuyruğu USDT',profitLoss:'Net K/Z USDT',closingCash:'Kasa devir USDT',totalNetwork:'Kümülatif ağ',previousNetwork:'Önceki gün ağ',growth:'Büyüme %',threshold:'Kritik sınır',paymentDetails:'Ödeme / ağ detayları',member:'Üye',type:'Tür',amount:'Tutar USDT',reference:'Referans',reportEnd:'Rapor sonu',noData:'Veri yok',starting:'Başlangıç',
}

const compact: Record<Exclude<ExportLanguageCode, 'en' | 'tr'>, string[]> = {
  ru:['КВИТАНЦИЯ ОБ ИНВЕСТИЦИОННОЙ ОПЕРАЦИИ','Подтверждённая сводка депозита цифрового актива','Номер документа','Дата создания','Дата подтверждения сети','Статус операции','Подтверждено','ДАННЫЕ УЧАСТНИКА','ФИО','Эл. почта','ДАННЫЕ ИНВЕСТИЦИИ','Сумма инвестиции','Сеть','Адрес получателя','Хеш операции','Электронно подтверждено','ДЕМО-СВОДКА GENERAL PARTNER (GP)','Пример интерфейса и экспорта документа','НОМЕР ДЕМО','ЗАПИСЬ УЧАСТНИКА','Код пользователя VELOX','ДЕМО-УСЛОВИЯ','ФИНАНСОВЫЙ ОТЧЁТ VELOX DEMO ЗА ДЕНЬ','ОТЧЁТ О РОСТЕ СЕТИ VELOX DEMO','Дата','Новые регистрации','Вся сеть','Рост %'],
  uk:['КВИТАНЦІЯ ІНВЕСТИЦІЙНОЇ ОПЕРАЦІЇ','Підтверджений підсумок депозиту цифрового активу','Номер документа','Дата створення','Дата підтвердження мережі','Статус операції','Підтверджено','ДАНІ УЧАСНИКА','ПІБ','Ел. пошта','ДАНІ ІНВЕСТИЦІЇ','Сума інвестиції','Мережа','Адреса отримувача','Хеш операції','Підтверджено електронно','ДЕМО-ПІДСУМОК GENERAL PARTNER (GP)','Приклад інтерфейсу та експорту документа','ДЕМО-НОМЕР','ЗАПИС УЧАСНИКА','Код користувача VELOX','ДЕМО-УМОВИ','ФІНАНСОВИЙ ЗВІТ VELOX DEMO ЗА ДЕНЬ','ЗВІТ ПРО ЗРОСТАННЯ МЕРЕЖІ VELOX DEMO','Дата','Нові реєстрації','Уся мережа','Зростання %'],
  es:['RECIBO DE OPERACIÓN DE INVERSIÓN','Resumen verificado del depósito de activo digital','Número de documento','Fecha de emisión','Fecha de confirmación de red','Estado de operación','Confirmado','INFORMACIÓN DEL MIEMBRO','Nombre completo','Correo electrónico','INFORMACIÓN DE INVERSIÓN','Importe de inversión','Red','Dirección receptora','Hash de transacción','Aprobado electrónicamente','RESUMEN DEMO GENERAL PARTNER (GP)','Ejemplo de interfaz y exportación','N.º DE REFERENCIA DEMO','REGISTRO DEL PARTICIPANTE','Código de usuario VELOX','TÉRMINOS DEMO','INFORME FINANCIERO DIARIO VELOX DEMO','INFORME DE CRECIMIENTO DE RED VELOX DEMO','Fecha','Nuevos registros','Red total','Crecimiento %'],
  pt:['RECIBO DE OPERAÇÃO DE INVESTIMENTO','Resumo verificado do depósito de ativo digital','Número do documento','Data de emissão','Data de confirmação da rede','Status da operação','Confirmado','INFORMAÇÕES DO MEMBRO','Nome completo','E-mail','INFORMAÇÕES DO INVESTIMENTO','Valor do investimento','Rede','Endereço de recebimento','Hash da transação','Aprovado eletronicamente','RESUMO DEMO GENERAL PARTNER (GP)','Exemplo de interface e exportação','N.º DE REFERÊNCIA DEMO','REGISTRO DO PARTICIPANTE','Código de usuário VELOX','TERMOS DEMO','RELATÓRIO FINANCEIRO DIÁRIO VELOX DEMO','RELATÓRIO DE CRESCIMENTO DA REDE VELOX DEMO','Data','Novos registros','Rede total','Crescimento %'],
  de:['INVESTITIONSTRANSAKTIONSBELEG','Bestätigte Übersicht der Einzahlung digitaler Vermögenswerte','Dokumentnummer','Ausstellungsdatum','Netzwerkbestätigung','Transaktionsstatus','Bestätigt','MITGLIEDSINFORMATIONEN','Vollständiger Name','E-Mail','INVESTITIONSINFORMATIONEN','Investitionsbetrag','Netzwerk','Empfangsadresse','Transaktions-Hash','Elektronisch bestätigt','GENERAL PARTNER (GP) DEMO-ZUSAMMENFASSUNG','Beispiel für Oberfläche und Dokumentexport','DEMO-REFERENZNR.','TEILNEHMERDATENSATZ','VELOX-Benutzercode','DEMO-BEDINGUNGEN','VELOX DEMO TAGESFINANZBERICHT','VELOX DEMO NETZWERKWACHSTUMSBERICHT','Datum','Neue Registrierungen','Gesamtes Netzwerk','Wachstum %'],
  it:['RICEVUTA OPERAZIONE DI INVESTIMENTO','Riepilogo verificato del deposito di asset digitali','Numero documento','Data emissione','Data conferma rete','Stato operazione','Confermato','INFORMAZIONI MEMBRO','Nome completo','E-mail','INFORMAZIONI INVESTIMENTO','Importo investimento','Rete','Indirizzo ricevente','Hash transazione','Approvato elettronicamente','RIEPILOGO DEMO GENERAL PARTNER (GP)','Esempio di interfaccia ed esportazione','N. RIFERIMENTO DEMO','REGISTRO PARTECIPANTE','Codice utente VELOX','TERMINI DEMO','REPORT FINANZIARIO GIORNALIERO VELOX DEMO','REPORT CRESCITA RETE VELOX DEMO','Data','Nuove registrazioni','Rete totale','Crescita %'],
  fr:['REÇU D’OPÉRATION D’INVESTISSEMENT','Résumé vérifié du dépôt d’actif numérique','Numéro du document','Date d’émission','Date de confirmation réseau','Statut de l’opération','Confirmé','INFORMATIONS DU MEMBRE','Nom complet','E-mail','INFORMATIONS D’INVESTISSEMENT','Montant investi','Réseau','Adresse destinataire','Hash de transaction','Approuvé électroniquement','RÉSUMÉ DÉMO GENERAL PARTNER (GP)','Exemple d’interface et d’export','N° DE RÉFÉRENCE DÉMO','DOSSIER PARTICIPANT','Code utilisateur VELOX','CONDITIONS DÉMO','RAPPORT FINANCIER QUOTIDIEN VELOX DEMO','RAPPORT DE CROISSANCE DU RÉSEAU VELOX DEMO','Date','Nouvelles inscriptions','Réseau total','Croissance %'],
  kk:['ИНВЕСТИЦИЯЛЫҚ ОПЕРАЦИЯ ТҮБІРТЕГІ','Расталған цифрлық актив салымының қорытындысы','Құжат нөмірі','Берілген күні','Желі растау күні','Операция күйі','Расталды','МҮШЕ АҚПАРАТЫ','Толық аты-жөні','Эл. пошта','ИНВЕСТИЦИЯ АҚПАРАТЫ','Инвестиция сомасы','Желі','Алушы мекенжайы','Транзакция хэші','Электронды расталды','GENERAL PARTNER (GP) ДЕМО ҚОРЫТЫНДЫСЫ','Интерфейс және экспорт үлгісі','ДЕМО АНЫҚТАМА №','ҚАТЫСУШЫ ЖАЗБАСЫ','VELOX пайдаланушы коды','ДЕМО ШАРТТАРЫ','VELOX DEMO КҮНДІК ҚАРЖЫ ЕСЕБІ','VELOX DEMO ЖЕЛІ ӨСІМІ ЕСЕБІ','Күні','Жаңа тіркелімдер','Жалпы желі','Өсім %'],
  bg:['РАЗПИСКА ЗА ИНВЕСТИЦИОННА ОПЕРАЦИЯ','Потвърдено резюме на депозит на цифров актив','Номер на документа','Дата на издаване','Дата на мрежово потвърждение','Статус на операцията','Потвърдено','ИНФОРМАЦИЯ ЗА ЧЛЕНА','Име и фамилия','Имейл','ИНВЕСТИЦИОННА ИНФОРМАЦИЯ','Инвестиционна сума','Мрежа','Адрес на получателя','Хеш на транзакцията','Одобрено електронно','GENERAL PARTNER (GP) ДЕМО РЕЗЮМЕ','Пример за интерфейс и експорт','ДЕМО РЕФЕРЕНТЕН №','ЗАПИС НА УЧАСТНИКА','VELOX потребителски код','ДЕМО УСЛОВИЯ','ДНЕВЕН ФИНАНСОВ ОТЧЕТ VELOX DEMO','ОТЧЕТ ЗА РЪСТ НА МРЕЖАТА VELOX DEMO','Дата','Нови регистрации','Обща мрежа','Ръст %'],
  id:['BUKTI TRANSAKSI INVESTASI','Ringkasan setoran aset digital terverifikasi','Nomor dokumen','Tanggal penerbitan','Tanggal konfirmasi jaringan','Status transaksi','Terkonfirmasi','INFORMASI ANGGOTA','Nama lengkap','Email','INFORMASI INVESTASI','Jumlah investasi','Jaringan','Alamat penerima','Hash transaksi','Disetujui secara elektronik','RINGKASAN DEMO GENERAL PARTNER (GP)','Contoh antarmuka dan ekspor dokumen','NO. REFERENSI DEMO','CATATAN PESERTA','Kode pengguna VELOX','KETENTUAN DEMO','LAPORAN KEUANGAN HARIAN VELOX DEMO','LAPORAN PERTUMBUHAN JARINGAN VELOX DEMO','Tanggal','Pendaftaran baru','Total jaringan','Pertumbuhan %'],
  ar:['إيصال معاملة استثمار','ملخص إيداع أصل رقمي تم التحقق منه','رقم المستند','تاريخ الإصدار','تاريخ تأكيد الشبكة','حالة المعاملة','مؤكد','معلومات العضو','الاسم الكامل','البريد الإلكتروني','معلومات الاستثمار','مبلغ الاستثمار','الشبكة','عنوان الاستلام','معرّف المعاملة','تم الاعتماد إلكترونياً','ملخص تجريبي للشريك العام (GP)','مثال للواجهة وتصدير المستند','رقم المرجع التجريبي','سجل المشارك','رمز مستخدم VELOX','الشروط التجريبية','التقرير المالي اليومي التجريبي VELOX','تقرير نمو الشبكة التجريبي VELOX','التاريخ','تسجيلات جديدة','إجمالي الشبكة','النمو %'],
  zh:['投资交易凭证','已验证的数字资产充值摘要','文件编号','签发日期','网络确认日期','交易状态','已确认','成员信息','姓名','电子邮件','投资信息','投资金额','网络','接收地址','交易哈希','电子批准','GENERAL PARTNER (GP) 演示摘要','界面与文件导出示例','演示参考号','参与者记录','VELOX 用户代码','演示条款','VELOX 演示每日财务报告','VELOX 演示网络增长报告','日期','新增注册','总网络','增长 %'],
  hu:['BEFEKTETÉSI TRANZAKCIÓS BIZONYLAT','Ellenőrzött digitáliseszköz-befizetés összegzése','Dokumentumszám','Kibocsátás dátuma','Hálózati megerősítés dátuma','Tranzakció állapota','Megerősítve','TAG ADATAI','Teljes név','E-mail','BEFEKTETÉSI ADATOK','Befektetési összeg','Hálózat','Fogadó cím','Tranzakció hash','Elektronikusan jóváhagyva','GENERAL PARTNER (GP) DEMÓ ÖSSZEFOGLALÓ','Felület- és exportpélda','DEMÓ HIVATKOZÁSI SZÁM','RÉSZTVEVŐI ADAT','VELOX felhasználói kód','DEMÓ FELTÉTELEK','VELOX DEMÓ NAPI PÉNZÜGYI JELENTÉS','VELOX DEMÓ HÁLÓZATNÖVEKEDÉSI JELENTÉS','Dátum','Új regisztrációk','Teljes hálózat','Növekedés %'],
  fa:['رسید تراکنش سرمایه‌گذاری','خلاصه واریز دارایی دیجیتال تأییدشده','شماره سند','تاریخ صدور','تاریخ تأیید شبکه','وضعیت تراکنش','تأیید شد','اطلاعات عضو','نام کامل','ایمیل','اطلاعات سرمایه‌گذاری','مبلغ سرمایه‌گذاری','شبکه','آدرس دریافت','هش تراکنش','تأیید الکترونیکی','خلاصه نمایشی GENERAL PARTNER (GP)','نمونه رابط و خروجی سند','شماره مرجع دمو','رکورد شرکت‌کننده','کد کاربری VELOX','شرایط دمو','گزارش مالی روزانه نمایشی VELOX','گزارش رشد شبکه نمایشی VELOX','تاریخ','ثبت‌نام‌های جدید','کل شبکه','رشد %'],
}

const compactKeys: Key[] = ['receiptTitle','receiptSubtitle','documentNumber','issueDate','confirmationDate','transactionStatus','confirmed','memberInfo','fullName','email','investmentInfo','investmentAmount','network','receivingAddress','transactionHash','electronicApproval','agreementTitle','agreementSubtitle','demoReference','participantRecord','userCode','clauses','financeTitle','growthTitle','date','newRegistrations','totalNetwork','growth']

const packs: Partial<Record<ExportLanguageCode, Pack>> = { tr }
for (const [language, values] of Object.entries(compact) as Array<[keyof typeof compact, string[]]>) {
  packs[language] = Object.fromEntries(compactKeys.map((key, index) => [key, values[index]])) as Pack
}

export function getExportLanguage(value: string | null | undefined) {
  const code = normalizeExportLanguage(value)
  const pack = packs[code] ?? {}
  return {
    code,
    locale: exportLocales[code],
    direction: code === 'ar' || code === 'fa' ? 'rtl' as const : 'ltr' as const,
    t: (key: Key) => pack[key] ?? en[key],
  }
}
